// Primitive Type
// 1. Number
var age = 31;
var weight = 78;
var height = 6.1;
var speckNumber = 0.50;
console.log(age);
console.log(weight);
console.log(height);
console.log(speckNumber);

console.log(age, weight, height, speckNumber);
// Primitive Type
// 1. Number
var age = 31;
var weight = 78;
var height = 6.1;
var speckNumber = 0.50;
console.log(age, weight, height, speckNumber);
var typeOfAge = typeof age;
console.log(typeOfAge);

console.log(typeof speckNumber);


console.log(age);
console.log(weight);
console.log(height);
console.log(speckNumber);

// 2. Boolean --> true or false
var isMarried = true;
var knowAngular = true; 
var isSoftwareEngineer = true;
var isBachelor = false; 
console.log(isBachelor);
var typeOfIsMarried =typeof isMarried;
console.log(typeOfIsMarried);
// Primitive Type
// 1. Number
var age = 31;
var weight = 78;
var height = 6.1;
var speckNumber = 0.50;
console.log(age, weight, height, speckNumber);
var typeOfAge = typeof age;
console.log(typeOfAge);

console.log(typeof speckNumber);


console.log("Age:", age);
console.log("Weight:", weight);
console.log(height);
console.log(speckNumber);

// 2. Boolean --> true or false
var isMarried = true;
var knowAngular = true; 
var isSoftwareEngineer = true;
var isBachelor = false; 
console.log(isBachelor);
var typeOfIsMarried = typeof isMarried;
console.log("Type of isMarried:", typeOfIsMarried);

// 3. String --> Sequence of character enclosed in '' or ""
var firstName = "Bill";
var position = 'Microsoft Co-founder'; 
var typeOfFirstName = typeof firstName;
console.log( "Type of variable -> firstName: ", typeOfFirstName );
console.log("Type of variable --> position: " , typeof position);
var city = "";
var typeOfCity = typeof city;

console.log("Type of variable City -->:", typeOfCity);
var address;
var typeOfAddress = typeof address;
console.log( "Type Of variable Address:",typeOfAddress);
var pin = null;
var typeOfpin = typeof pin;
console.log("Type of Variable null:",typeOfpin);


