var company = "Accenture";
function stringBasics(){
    console.log("My dream company is: ",company);
    console.log(/----------------------------------------------------------/);
    var hobby1 = "Writing";
var hobby2 = "Reading";
var hobby3 = "Cooking";
 console.log("My all hobbies:",hobby1,hobby2, hobby3);
var hobby1Length = hobby1.length;
// console.log("Number of Char in first hobby:",hobby1Length);
var hobby2Length = hobby2.length;
// console.log("Number of Char in Second hobby:",hobby2Length);
var hobby3Length = hobby3.length;
// console.log("Number of Char in Third hobby:",hobby3Length);
console.log(/----------------------------------------------------------/);
console.log("Sum Of Total Number Of Char Is Avaliable in all Hobbies is:  ",hobby1Length+hobby2Length+hobby3Length);
}
stringBasics();



