


var nmb = "***Data Type Number***";
console.log(nmb);
var age = 27;

var typeOfAge = typeof age;
console.log( "AGE:", age ,     "Type:", typeOfAge);
var nmr = "***Data Type String***";
console.log(nmr);
var str = "Codemine Technology";

var typeOfStr = typeof str;
console.log("STR:", str,   "Type:",typeOfStr);
var nme = "***Data Type Boolean***";
console.log(nme);
var isMarried = true;

var typeOfIsMarried = typeof isMarried;
console.log("ISMARRIED:", isMarried,  "Type:", typeOfIsMarried);

var diff =" ****Difference between null and undefined****";
console.log(diff);


 var nu ="null means we can declared variable and assinged it's value as null and undefined means we can defined variable but can't initilized so we get type of null is object and type of undefined is undefined."
 console.log(nu);
 var st = null;
var typeOfSt = typeof st;
console.log(typeOfSt);


var sr;
var typeOfSr = typeof sr;
console.log(typeOfSr);








