var bankName;
var typeOfBankName = typeof bankName;
console.log( "BankName:",bankName, "type of variable BankName:",typeOfBankName);// befor Initilization


bankName = "SBI Bank";

var typeOfBankName = typeof bankName;
console.log("BankName:",bankName,"Type of variable bankName:",typeOfBankName);//after Initilization

var marks = "90%";
var typeOfMarks = typeof marks;
console.log("Type of variable marks:",typeOfMarks ,"Marks:", marks);

var isWorking;
console.log(isWorking); //befor Initilization

var isWorking = true;
console.log(isWorking);// after Initilization


var totalCount = "Hundred and Seven";//variable declaration and initilization
var typeOfTotalCount = typeof totalCount;
console.log("TotalCount:",totalCount,"Type of variable TotalCount:",typeOfTotalCount);//log console with data type and its value

var totalCount = 107; //Update variable
var typeOfTotalCount = typeof totalCount;
console.log("TotalCount:",totalCount,"Type of variable TotalCount:",typeOfTotalCount);
