var st = 0;
var st1 = '';
var result = (0 == '');

console.log( `1. ${result} `);
console.log(`1 Reason ).here one operend value is zere and other is in the form of string there is only single space and equal to operatore evaluate true if there value is same not check its data type.and here value is same.`); 

var st2 = 0;
var st3 = '0';
var result1 = (0 == '0')
console.log(`2. result1`);
console.log(`2 Reason ).here one operend value is zere and other oprand value is zero but in string formate. but equal to operatore evaluate true if there value is same not check its data type.and here value is same.`); 
var st4 = 0;
var st5 = false;
var res = Number(false);
console.log(res);
var result2 = ( 0 == false);
console.log(`3. result2`);
var st6 = null;
var st7 = undefined;
var result3 = ( null == undefined);
console.log(result3);
