console.log(`1) numbers from 5 to 15 incrementing by 1`);

let i = 5;
while (i<=15) {
    console.log(` ${i}`);
    i = i + 1;
}
console.log(`2) numbers from 5 to 15 decrementing by 1`);
let j = 50;
while (j>=40) {
    console.log(` ${j}`);
    j = j - 1;
}
console.log(`3) first 15 odd number`);
let k = 0;
while (k<=30) {
   if (k%2 != 0) {
    console.log(`${k}`);
   }
   k++;
}
console.log(`4) first 10 even number`);
let l = 2;
while (l<=20) {
   if (l%2 == 0) {
    console.log(`${l}`);
   }
   l++;
}
console.log(`5) Table  of 5`);
let m = 5;
while (m<=50) {
    console.log(` ${m}`);
    m = m + 5;
}
console.log(`6) Table  of 10`);
let n = 10;
while (n<=100) {
    console.log(` ${n}`);
    n = n + 10;
}
console.log(`7) Table  of 10 in reverse order`);
let o = 100;
while (o>=10) {
    console.log(` ${o}`);
    o = o - 10;
}

