// const arrayNums = [12,13,25,48,68,79,46,52,36];
// const sumArrayNums = arrayNums.reduce((runningTotal, value) => {
// return runningTotal+value;
// });
// console.log(sumArrayNums);
// const evenNums= arrayNums.filter((element) => {
// return element%2 ==0;
// });
// console.log(evenNums);
// const evenOdds= arrayNums.filter((element) => {
//     return element%2 !=0;
//     });
//     console.log(evenOdds);
//     console.log(`----------spread Operator --------`);
//     let array = ["teju", "ganesh","nilesh", "varsha", "snehal","akash"];
//     console.log(...array);
//     console.log(`-----------rest Parameter-------`);
//     function display(...num1) {
//         console.log(num1);
        
//     };
//     display(10,20,30);
//     display("I love","javascript");
//     console.log(`--------function default parameter ----------`);
//     function multiplication(x, y=2) {
//         console.log(x*y);
        
//     };
//     multiplication(20,10);
//     multiplication(50);
//     console.log(`----------object destructuring------`);
//     const person = {
//         firstName : "Teju",
//         age : 27,
//         grad : "Msc",
//     }
//     let first_name = person.firstName;
//     let age = person.age;
//     console.log(first_name,age );
//     console.log(`----------array destruction----------`);
//     const fruits = ["mango", "apple","banana", "pinaple", "orange"];
//     const fruitsApple = fruits[1];
//     const fruitsOrange = fruits[4];
//     console.log(fruitsApple,fruitsOrange );
//     let [fruit1,fruit2, fruit3 = "Jack Fruit", fruit4 = "papaya"] = fruits;
//     console.log(fruit1,fruit2,fruit3,fruit4);
const arrayNums = [10,20,10,20,45,4,6,3,5,6,10];



